find_path(MPFR_INCLUDE_DIR_DEBUG
	NAMES mpfr.h
	PATHS
		ENV MPFR_ROOT_DEBUG
		ENV MPFR_INCLUDE_DIR_DEBUG
		${MPFR_ROOT_DEBUG}
		/usr
		/usr/local
	PATH_SUFFIXES include
)

find_path(MPFR_INCLUDE_DIR_RELEASE
	NAMES mpfr.h
	PATHS
		ENV MPFR_ROOT_RELEASE
		ENV MPFR_INCLUDE_DIR_RELEASE
		${MPFR_ROOT_RELEASE}
		/usr
		/usr/local
	PATH_SUFFIXES include
)

find_library(MPFR_LIBRARY_DEBUG
	NAMES mpfr
	PATHS
		ENV MPFR_ROOT_DEBUG
		ENV MPFR_LIB_DIR_DEBUG
		${MPFR_ROOT_DEBUG}
		/usr
		/usr/local
	PATH_SUFFIXES lib
)

find_library(MPFR_LIBRARY_RELEASE
	NAMES mpfr
	PATHS
		ENV MPFR_ROOT_RELEASE
		ENV MPFR_LIB_DIR_RELEASE
		${MPFR_ROOT_RELEASE}
		/usr
		/usr/local
	PATH_SUFFIXES lib
)

mark_as_advanced(MPFR_INCLUDE_DIR_DEBUG MPFR_LIBRARY_DEBUG)
mark_as_advanced(MPFR_INCLUDE_DIR_RELEASE MPFR_LIBRARY_RELEASE)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(MPFR
	REQUIRED_VARS
		MPFR_INCLUDE_DIR_DEBUG
		MPFR_INCLUDE_DIR_RELEASE
		MPFR_LIBRARY_DEBUG
		MPFR_LIBRARY_RELEASE
)

find_package(GMP REQUIRED)
