name: C/C++ CI

on:
  push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: requirement
      run: |
        sudo apt update
        sudo apt install libgmp-dev libmpfr-dev
    - name: configure debug
      run: mkdir build && cd build && cmake -DGMP_INCLUDE_DIR=/usr/include -DGMP_LIBRARY=/usr/lib/x86_64-linux-gnu -DMPFR_INCLUDE_DIR=/usr/include -DMPFR_LIBRARY=/usr/lib/x86_64-linux-gnu -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=~/local ..
    - name: make debug
      run: make -j4
    - name: make debug install
      run: make install
    - name: configure release
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: make release
      run: make -j4
    - name: make release install
      run: make install
