name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_matrix:
    name: build (${{ matrix.build_type }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
    - name: requirement
      run: |
        sudo apt-get update
        sudo apt-get install -y libgmp-dev libmpfr-dev
    - name: configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_INSTALL_PREFIX="$HOME/local"
    - name: make
      run: cmake --build build --parallel 2
    - name: make install
      run: cmake --install build

  build:
    runs-on: ubuntu-latest
    needs: build_matrix
    if: ${{ always() }}
    steps:
    - name: Check all build configurations
      env:
        BUILD_RESULT: ${{ needs.build_matrix.result }}
      run: test "$BUILD_RESULT" = success
