name: C/C++ CI

on:
  push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: requirement
      run: |
        sudo apt update
        sudo apt install libgmp-dev libmpfr-dev
    - name: configure
      run: |
        mkdir build
        cd build
        export INCLUDE=/usr/include:/usr/include
        export CPATH=/usr/include:/usr/include
        export CPLUS_INCLUDE_PATH=/usr/include
        export CXX_INCLUDE_PATH=/usr/include
        export C_INCLUDE_PATH=/usr/include
        echo $INCLUDE
        echo $CPATH
        cmake -DGMP_INCLUDE_DIR=/usr/include -DGMP_LIBRARY=/usr/lib/x86_64-linux-gnu -DGMPXX_LIBRARY=/usr/lib/x86_64-linux-gnu -DMPFR_INCLUDE_DIR=/usr/include -DMPFR_LIBRARY=/usr/lib/x86_64-linux-gnu -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=~/local ..
    - name: make debug
      run: |
        cd build
        export INCLUDE=/usr/include:/usr/include
        export CPATH=/usr/include:/usr/include
        export CPLUS_INCLUDE_PATH=/usr/include
        export CXX_INCLUDE_PATH=/usr/include
        export C_INCLUDE_PATH=/usr/include
        echo -e "#include <iostream>\nint main(){std::cout<<\"hello\"<<std::endl;return 0;}" > hello.cpp
        cat hello.cpp
        g++ hello.cpp
        make install -j4
    - name: configure release
      run: |
        cd build
        export INCLUDE=/usr/include:/usr/include
        export CPATH=/usr/include:/usr/include
        export CPLUS_INCLUDE_PATH=/usr/include
        export CXX_INCLUDE_PATH=/usr/include
        export C_INCLUDE_PATH=/usr/include
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make install -j4
